/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package lab.pkg6_mauricioaguilera;

import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author mauri
 */
public class plataforma extends javax.swing.JFrame {

    /**
     * Creates new form plataforma
     */
    public plataforma() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jd_menu = new javax.swing.JDialog();
        jScrollPane3 = new javax.swing.JScrollPane();
        ta_datos = new javax.swing.JTextArea();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jt_peli = new javax.swing.JTree();
        jLabel6 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jd_peli = new javax.swing.JDialog();
        tf_nombrepeli = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        sp_tiempopeli = new javax.swing.JSpinner();
        jLabel9 = new javax.swing.JLabel();
        cb_catepeli = new javax.swing.JComboBox<>();
        jLabel10 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        ta_actorpeli = new javax.swing.JTextArea();
        jLabel11 = new javax.swing.JLabel();
        tf_director = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        tf_compania = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        cb_idiomapeli = new javax.swing.JComboBox<>();
        jLabel14 = new javax.swing.JLabel();
        rb_sipeli = new javax.swing.JRadioButton();
        rb_nopeli = new javax.swing.JRadioButton();
        jLabel15 = new javax.swing.JLabel();
        rb_sipeli1 = new javax.swing.JRadioButton();
        rb_nopeli1 = new javax.swing.JRadioButton();
        jPanel3 = new javax.swing.JPanel();
        jButton3 = new javax.swing.JButton();
        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        pf_pass = new javax.swing.JPasswordField();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        tf_usuario = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();

        jd_menu.setMaximumSize(new java.awt.Dimension(680, 460));
        jd_menu.setMinimumSize(new java.awt.Dimension(680, 460));
        jd_menu.setPreferredSize(new java.awt.Dimension(680, 460));
        jd_menu.setResizable(false);
        jd_menu.setSize(new java.awt.Dimension(680, 460));
        jd_menu.getContentPane().setLayout(null);

        ta_datos.setBackground(new java.awt.Color(102, 102, 102));
        ta_datos.setColumns(20);
        ta_datos.setForeground(new java.awt.Color(255, 255, 255));
        ta_datos.setRows(5);
        jScrollPane3.setViewportView(ta_datos);

        jd_menu.getContentPane().add(jScrollPane3);
        jScrollPane3.setBounds(349, 83, 300, 322);

        jPanel2.setBackground(new java.awt.Color(0, 0, 0));

        jt_peli.setBackground(new java.awt.Color(102, 102, 102));
        jt_peli.setForeground(new java.awt.Color(255, 255, 255));
        javax.swing.tree.DefaultMutableTreeNode treeNode1 = new javax.swing.tree.DefaultMutableTreeNode("NESFLIS");
        jt_peli.setModel(new javax.swing.tree.DefaultTreeModel(treeNode1));
        jScrollPane1.setViewportView(jt_peli);

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Bienvenido");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(195, 195, 195)
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 263, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(252, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(42, Short.MAX_VALUE)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(75, 75, 75))
        );

        jd_menu.getContentPane().add(jPanel2);
        jPanel2.setBounds(-10, -30, 710, 510);

        jMenuBar1.setBackground(new java.awt.Color(102, 102, 102));
        jMenuBar1.setForeground(new java.awt.Color(102, 102, 102));

        jMenu1.setText("Opciones");
        jMenu1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu1ActionPerformed(evt);
            }
        });

        jMenuItem1.setText("Agregar Pelicula");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuItem2.setText("Agregar Serie");
        jMenu1.add(jMenuItem2);

        jMenuItem3.setText("Guardar Cambios");
        jMenu1.add(jMenuItem3);

        jMenuItem4.setText("Log Out");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem4);

        jMenuBar1.add(jMenu1);

        jd_menu.setJMenuBar(jMenuBar1);

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane2.setViewportView(jTextArea1);

        jd_peli.setTitle("Agregar Pelicula");
        jd_peli.setLocationByPlatform(true);
        jd_peli.setMaximumSize(new java.awt.Dimension(680, 460));
        jd_peli.setMinimumSize(new java.awt.Dimension(680, 460));
        jd_peli.setPreferredSize(new java.awt.Dimension(680, 460));
        jd_peli.setResizable(false);
        jd_peli.setSize(new java.awt.Dimension(680, 460));
        jd_peli.getContentPane().setLayout(null);

        tf_nombrepeli.setBackground(new java.awt.Color(51, 51, 51));
        tf_nombrepeli.setForeground(new java.awt.Color(255, 255, 255));
        jd_peli.getContentPane().add(tf_nombrepeli);
        tf_nombrepeli.setBounds(158, 69, 166, 20);

        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Nombre");
        jd_peli.getContentPane().add(jLabel7);
        jLabel7.setBounds(33, 72, 37, 14);

        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Duracion (Minutos)");
        jd_peli.getContentPane().add(jLabel8);
        jLabel8.setBounds(33, 110, 90, 14);
        jd_peli.getContentPane().add(sp_tiempopeli);
        sp_tiempopeli.setBounds(265, 107, 59, 20);

        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Categoria");
        jd_peli.getContentPane().add(jLabel9);
        jLabel9.setBounds(33, 149, 47, 14);

        cb_catepeli.setBackground(new java.awt.Color(51, 51, 51));
        cb_catepeli.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Suspenso", "Terror", "Acción", "Románticas", "Ciencia Ficción", "Animación", "Fantasía" }));
        jd_peli.getContentPane().add(cb_catepeli);
        cb_catepeli.setBounds(158, 146, 166, 20);

        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Actores");
        jd_peli.getContentPane().add(jLabel10);
        jLabel10.setBounds(33, 183, 37, 14);

        ta_actorpeli.setBackground(new java.awt.Color(51, 51, 51));
        ta_actorpeli.setColumns(20);
        ta_actorpeli.setForeground(new java.awt.Color(255, 255, 255));
        ta_actorpeli.setRows(5);
        jScrollPane4.setViewportView(ta_actorpeli);

        jd_peli.getContentPane().add(jScrollPane4);
        jScrollPane4.setBounds(158, 183, 166, 96);

        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Director");
        jd_peli.getContentPane().add(jLabel11);
        jLabel11.setBounds(33, 310, 38, 14);

        tf_director.setBackground(new java.awt.Color(51, 51, 51));
        tf_director.setForeground(new java.awt.Color(255, 255, 255));
        jd_peli.getContentPane().add(tf_director);
        tf_director.setBounds(158, 307, 166, 20);

        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Compania");
        jd_peli.getContentPane().add(jLabel12);
        jLabel12.setBounds(363, 72, 47, 14);

        tf_compania.setBackground(new java.awt.Color(51, 51, 51));
        tf_compania.setForeground(new java.awt.Color(255, 255, 255));
        jd_peli.getContentPane().add(tf_compania);
        tf_compania.setBounds(467, 69, 166, 20);

        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Idioma");
        jd_peli.getContentPane().add(jLabel13);
        jLabel13.setBounds(363, 110, 32, 14);

        cb_idiomapeli.setBackground(new java.awt.Color(51, 51, 51));
        cb_idiomapeli.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Español", "Ingles", "Alemán y Francés" }));
        jd_peli.getContentPane().add(cb_idiomapeli);
        cb_idiomapeli.setBounds(467, 107, 166, 20);

        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("Doblaje");
        jd_peli.getContentPane().add(jLabel14);
        jLabel14.setBounds(363, 149, 36, 14);

        rb_sipeli.setBackground(new java.awt.Color(0, 0, 0));
        buttonGroup1.add(rb_sipeli);
        rb_sipeli.setForeground(new java.awt.Color(255, 255, 255));
        rb_sipeli.setText("Si");
        jd_peli.getContentPane().add(rb_sipeli);
        rb_sipeli.setBounds(509, 145, 33, 23);

        rb_nopeli.setBackground(new java.awt.Color(0, 0, 0));
        buttonGroup1.add(rb_nopeli);
        rb_nopeli.setForeground(new java.awt.Color(255, 255, 255));
        rb_nopeli.setText("No");
        jd_peli.getContentPane().add(rb_nopeli);
        rb_nopeli.setBounds(572, 145, 39, 23);

        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("Subtitulos");
        jd_peli.getContentPane().add(jLabel15);
        jLabel15.setBounds(363, 187, 47, 14);

        rb_sipeli1.setBackground(new java.awt.Color(0, 0, 0));
        buttonGroup2.add(rb_sipeli1);
        rb_sipeli1.setForeground(new java.awt.Color(255, 255, 255));
        rb_sipeli1.setText("Si");
        jd_peli.getContentPane().add(rb_sipeli1);
        rb_sipeli1.setBounds(509, 183, 33, 23);

        rb_nopeli1.setBackground(new java.awt.Color(0, 0, 0));
        buttonGroup2.add(rb_nopeli1);
        rb_nopeli1.setForeground(new java.awt.Color(255, 255, 255));
        rb_nopeli1.setText("No");
        jd_peli.getContentPane().add(rb_nopeli1);
        rb_nopeli1.setBounds(572, 183, 39, 23);

        jPanel3.setBackground(new java.awt.Color(0, 0, 0));

        jButton3.setBackground(new java.awt.Color(255, 255, 255));
        jButton3.setForeground(new java.awt.Color(204, 0, 0));
        jButton3.setText("Guardar");
        jButton3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton3MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(200, 200, 200)
                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 318, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(202, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(393, Short.MAX_VALUE)
                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(60, 60, 60))
        );

        jd_peli.getContentPane().add(jPanel3);
        jPanel3.setBounds(-20, -10, 720, 490);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 0, 0));
        setForeground(new java.awt.Color(0, 0, 0));
        setMaximumSize(new java.awt.Dimension(643, 460));
        setMinimumSize(new java.awt.Dimension(643, 460));
        setResizable(false);
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Bodoni MT Poster Compressed", 0, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(204, 0, 0));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("NESFLIS");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(174, 53, 241, 46);

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Programa experimental para la administracion de ");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(146, 110, 300, 17);

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("pleiculas y series");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(242, 133, 98, 17);

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));

        jButton1.setBackground(new java.awt.Color(255, 255, 255));
        jButton1.setForeground(new java.awt.Color(204, 0, 0));
        jButton1.setText("Log In");
        jButton1.setToolTipText("");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });

        pf_pass.setBackground(new java.awt.Color(51, 51, 51));
        pf_pass.setForeground(new java.awt.Color(255, 255, 255));

        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Contraseña");

        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Nombre");

        tf_usuario.setBackground(new java.awt.Color(51, 51, 51));
        tf_usuario.setForeground(new java.awt.Color(255, 255, 255));

        jButton2.setBackground(new java.awt.Color(255, 255, 255));
        jButton2.setForeground(new java.awt.Color(204, 0, 0));
        jButton2.setText("Listado de cuentas");
        jButton2.setToolTipText("");
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton2MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(171, 171, 171)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5))
                        .addGap(34, 34, 34)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(pf_pass, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tf_usuario, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(222, 222, 222)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(335, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(119, 119, 119))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(234, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tf_usuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(38, 38, 38)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(pf_pass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(57, 57, 57)
                .addComponent(jButton2)
                .addGap(136, 136, 136))
        );

        getContentPane().add(jPanel1);
        jPanel1.setBounds(-40, -30, 750, 590);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        // TODO add your handling code here:
        AdministarUsuarios au = new AdministarUsuarios("./Usuarios.txt");
        usuarios = au.CargarArchivo();
        boolean val=false;
        for (int i = 0; i < usuarios.size(); i++) {
            if (tf_usuario.getText().equals(usuarios.get(i).getNombre()) && pf_pass.getText().equals(usuarios.get(i).getPass())){
                val=true;
            }
        }
        if (val){
            tf_usuario.setText("");
            pf_pass.setText("");
            jd_menu.setModal(true);
            jd_menu.pack();
            jd_menu.setLocationRelativeTo(this);
            jd_menu.setVisible(true);
        }
        else{
            JOptionPane.showMessageDialog(this, "El nombre y la contraseña no coinciden");
        }
    }//GEN-LAST:event_jButton1MouseClicked

    private void jButton2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseClicked
        // TODO add your handling code here:
        AdministarUsuarios au = new AdministarUsuarios("./Usuarios.txt");
        usuarios = au.CargarArchivo();
        String temp="";
        for (int i = 0; i < usuarios.size(); i++) {
            temp+=usuarios.get(i)+"\n";
        }
        JOptionPane.showMessageDialog(this, temp);
    }//GEN-LAST:event_jButton2MouseClicked

    private void jMenu1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu1ActionPerformed

    }//GEN-LAST:event_jMenu1ActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        // TODO add your handling code here:
        jd_menu.setVisible(false);
        jd_menu.setModal(false);
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
        jd_peli.setModal(true);
        jd_peli.pack();
        jd_peli.setLocationRelativeTo(this);
        jd_peli.setVisible(true);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jButton3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton3MouseClicked
        // TODO add your handling code here:
        String nombre;
        int tiempo;
        String categoria;
        String actores;
        String director;
        String compania;
        String idioma;
        String doblaje="";
        String subtitulos="";
        try {
            nombre= tf_nombrepeli.getText();
            tiempo= (Integer)sp_tiempopeli.getValue();
            categoria = cb_catepeli.getSelectedItem().toString();
            actores = ta_actorpeli.getText();
            director = tf_director.getText();
            compania = tf_compania.getText();
            idioma = cb_idiomapeli.getSelectedItem().toString();
            if (rb_sipeli.isSelected()){
                doblaje = "si";
            }
            else{
                doblaje = "no";
            }
            if (rb_sipeli1.isSelected()) {
                subtitulos="si";
            } else {
                subtitulos="no";
            }
            
            
        } catch (Exception e) {
        }
    }//GEN-LAST:event_jButton3MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(plataforma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(plataforma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(plataforma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(plataforma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new plataforma().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JComboBox<String> cb_catepeli;
    private javax.swing.JComboBox<String> cb_idiomapeli;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JDialog jd_menu;
    private javax.swing.JDialog jd_peli;
    private javax.swing.JTree jt_peli;
    private javax.swing.JPasswordField pf_pass;
    private javax.swing.JRadioButton rb_nopeli;
    private javax.swing.JRadioButton rb_nopeli1;
    private javax.swing.JRadioButton rb_sipeli;
    private javax.swing.JRadioButton rb_sipeli1;
    private javax.swing.JSpinner sp_tiempopeli;
    private javax.swing.JTextArea ta_actorpeli;
    private javax.swing.JTextArea ta_datos;
    private javax.swing.JTextField tf_compania;
    private javax.swing.JTextField tf_director;
    private javax.swing.JTextField tf_nombrepeli;
    private javax.swing.JTextField tf_usuario;
    // End of variables declaration//GEN-END:variables
ArrayList <Usuario> usuarios = new ArrayList();
ArrayList <Pelicula> peliculas = new ArrayList();
ArrayList <Serie> series = new ArrayList();
}
